### ISSUE TITLE
contributors.svg

### ISSUE THREAD

**Issue by zuramai** [himtiunesa2020/collaborators#1]
Kenapa tidak pakai github actions seperti ini untuk auto-generate collaborator?

https://github.com/wow-actions/contributors-list

**Comment by viandwi24** [comment]
alo gi, ini bukan contributors :v kalo contributors di repo repo gw pake svg itu. ini repo cuman nyatet orang orang doang yang punya github wkwk

**Comment by zuramai** [comment]
akwoakwoakw
